import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white px-6 py-4 flex justify-center space-x-6 shadow-md">
        <Link href="/Home" className="hover:text-yellow-400 transition-colors" >Home</Link>
        <Link href="/About">About</Link>
        <Link href="/Services">Services</Link>
        <Link href="/Contact">Contact</Link>
        
      </nav>
        {children}

      </body>
    </html>
  );
}
